need-configuration:
  active-type: "increase"
  increase:
    start: 100
    value: 100
    max: 100
  multiply:
    start: 100
    value: 1.37
    max: 100
  static:
    value: "100;150;200;250" # start need = 100, max level = 4