name: PerfectStone
version: '${version}'
main: me.rennvo.perfectstone.PerfectStonePlugin
authors: [ renNvo ]
website: github.com/renNvo
commands:
  drop:
    description: command for stone state
    aliases:
      - stone
